name: üñåÔ∏è Renovate
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get hojmark-renovate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: Iv23liWqEqKI4vhrLE1i # hojmark-renovate Client ID
          private-key: ${{ secrets.RENOVATE_APP_PK }}

      - name: Run Renovate
        run: |
          docker run --rm \
            -e RENOVATE_LOG_LEVEL=info \
            -e RENOVATE_PLATFORM=github \
            -e RENOVATE_REPOSITORIES=hojmark/drift \
            -e RENOVATE_TOKEN=${{ steps.app-token.outputs.token }} \
            renovate/renovate:latest