name: üñåÔ∏è Renovate
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Renovate log level"
        required: false
        default: 'info'
        type: choice
        options:
          - 'info'
          - 'debug'
  schedule:
    - cron: '0 6 * * WED' # At 06:00 AM, only on Wednesday

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: Iv23liWqEqKI4vhrLE1i # hojmark-renovate Client ID
          private-key: ${{ secrets.RENOVATE_APP_PK }}

      - name: Run Renovate
        run: |
          docker run --rm \
            -e RENOVATE_LOG_LEVEL=info \
            -e RENOVATE_PLATFORM=github \
            -e RENOVATE_REPOSITORIES=hojmark/drift \
            -e RENOVATE_TOKEN=${{ steps.app-token.outputs.token }} \
            renovate/renovate:latest